drop type public.game_statuses;
create type public.game_statuses as enum (
    'Created',
    'Started',
    'Ended'
);

create table public.games (
    id bigint generated by default as identity primary key,
    name text not null,
    status game_statuses not null,
    participation_order bigint ARRAY,
    current_participation_id bigint
);

create table public.players (
    id bigint generated by default as identity primary key,
    name text not null
);

create table public.participations (
    game_id bigint not null,
    player_id bigint not null,
    player_ready boolean not null default false,
    bet_quantity smallint,
    bet_value smallint,
    primary key (game_id, player_id),
    constraint fk_game_id
        foreign key(game_id)
        references games(id),
    constraint fk_player_id
        foreign key(player_id)
        references players(id)
);

alter publication supabase_realtime add table games;
alter publication supabase_realtime add table players;
alter publication supabase_realtime add table participations;

comment on table games is 'The available, active, and completed games.';
comment on column games.name is 'The name of the game.';
comment on column games.status is 'The status of the game.';
comment on column games.participation_order is 'The order of play for participations.';
comment on column games.current_participation_id is 'The current active participation id for the game.';

comment on table players is 'All players in all games.';
comment on column players.name is 'A player name.';

comment on table participations is 'Participations - a player in a particular game and their dice details.';
comment on column participations.game_id is 'The game id for which this participation is playing.';
comment on column participations.player_id is 'The player id for this participation.';
comment on column participations.player_ready is 'Whether this player is ready for this participation.';
comment on column participations.bet_quantity is 'The current bet quantity for this participation.';
comment on column participations.bet_value is 'The current bet value this participation.';