name: dice
description: A game of liar's dice.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  auto_route: ^3.2.4
  bloc: ^8.0.3
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  json_serializable: ^6.2.0
  lazy_evaluation: ^1.1.0
  shared_preferences: ^2.0.6
  stream_transform: ^2.0.0
  supabase: ^0.3.1+1
  vector_math: ^2.1.0

dev_dependencies:
  auto_route_generator: ^3.2.3
  build_runner: null
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1

flutter:
  assets:
    - .env

  uses-material-design: true
