name: dice
description: A game of liar's dice.

publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch --delete-conflicting-outputs
  serve: flutter run -d web-server --web-hostname 0.0.0.0 --web-port 8989

dependencies:
  auto_route: ^4.0.1
  bloc: ^8.0.3
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  lazy_evaluation: ^1.1.0
  package_info_plus: ^1.4.2
  shared_preferences: ^2.0.6
  stream_transform: ^2.0.0
  supabase: ^0.3.1+1
  vector_math: ^2.1.0

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: null
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1

flutter:
  assets:
    - .env

  uses-material-design: true
