name: dice
description: A game of liar's dice.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^7.0.0
  cupertino_icons: ^1.0.2
  cloud_firestore: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.14.2

flutter:
  uses-material-design: true
